include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/localization/generated/**"

linter:
  rules:
    public_member_api_docs: false
    avoid_types_on_closure_parameters: false
    depend_on_referenced_packages: false
    avoid_catches_without_on_clauses: false
    null_check_on_nullable_type_parameter: false
    use_if_null_to_convert_nulls_to_bools: false
    avoid_positional_boolean_parameters: false
    omit_local_variable_types: false
    use_build_context_synchronously: false
    prefer_constructors_over_static_methods: false
    unnecessary_lambdas: false
    type_annotate_public_apis: false
    always_use_package_imports: true