name: money_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: 3.19.2

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Localization 19.4.38м
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter
  provider: 6.0.5
  # Logic
  flutter_bloc: 8.1.5
  hydrated_bloc: 9.1.5

  injectable: 2.1.2
  get_it: 7.6.0
  # UI
  gap: 3.0.1
  flutter_slidable: 3.1.0
  currency_text_input_formatter: 2.2.3
  flutter_keyboard_visibility: 6.0.0
  flutter_svg: 2.0.9
  material_segmented_control: 5.0.0
  octo_image: 2.0.0
  cached_network_image: 3.3.1
  flutter_blurhash: 0.8.2
  flutter_staggered_grid_view: 0.7.0

  # графики
  fl_chart: 0.68.0
  # выбор промежутка времени
  syncfusion_flutter_datepicker: 19.4.38
  # анимация
  animated_size_and_fade: 4.0.0
  another_flushbar: 1.12.30
  auto_size_text: 3.0.0
  # Persisting
  shared_preferences: 2.2.1

  # Routing
  auto_route: 8.1.3

  # Logging
  stack_trace: 1.11.1
  logging: 1.2.0
  pretty_dio_logger: 1.3.1

  # Utils
  stream_transform: 2.1.0
  platform_info: 4.0.2
  path: 1.9.0
  path_provider: 2.1.0
  json_annotation: 4.8.1

  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lints
  flutter_lints: 3.0.2

  # Utils
  json_serializable: 6.7.1
  flutter_gen_runner: 5.3.2
  build_runner: 2.4.6
  auto_route_generator: 8.0.0
  injectable_generator: 2.1.6

  intl_utils: 2.8.5
  freezed: 2.5.2

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/icons/transaction_category/
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic

flutter_gen:
  output: lib/app/assets/generated
  line_length: 80
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: ru
  arb_dir: lib/localization/translations
  output_dir: lib/localization/generated